[package]
authors = ["Saverio Miroddi <saverio.pub2@gmail.com>"]
edition = "2018"
name = "hands_on_algos"
version = "0.1.0"

[dependencies]
fastrand = "1.4.1"
indoc = "1.0.3"
rand = "0.8.0"
termion = "1.5.6"
